volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_redis_data: {}
  production_media_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cactus_cat_software_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - production_media_data:/app/cactus_cat_software/media
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cactus_cat_software_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:7.2
    volumes:
      - production_redis_data:/data

  nginx:
    image: docker.io/nginx:1.25-alpine
    depends_on:
      - django
    volumes:
      - production_media_data:/usr/share/nginx/media:ro
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cactus_cat_software_production_traefik
    depends_on:
      - nginx
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  celeryworker:
    <<: *django
    image: cactus_cat_software_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: cactus_cat_software_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: cactus_cat_software_production_flower
    command: /start-flower
