# Generated by Django 5.2.9 on 2026-01-03 02:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50, verbose_name='Icon Class')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Package Name')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(help_text='Brief description for catalog cards', max_length=255, verbose_name='Short Description')),
                ('features', models.TextField(help_text='One feature per line', verbose_name='Features')),
                ('description', models.TextField(help_text='Detailed description for service detail page', verbose_name='Full Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('is_price_starting_from', models.BooleanField(default=False, help_text='Display as "Starting from $X"', verbose_name='Starting From Price')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Package Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('estimated_delivery_days', models.IntegerField(blank=True, null=True, verbose_name='Estimated Delivery (Days)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='services.servicecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
