# Generated by Django 5.2.9 on 2026-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rate if client opts to subscribe instead of buying outright', max_digits=10, null=True, verbose_name='Monthly Subscription Price'),
        ),
    ]
