# Generated by Django 5.2.9 on 2026-03-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicepackage_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='setup_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upfront deposit for the financed/subscription option', max_digits=10, null=True, verbose_name='Financing Setup Fee'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rate for the financed option (shown in financing popup)', max_digits=10, null=True, verbose_name='Monthly Financing Price'),
        ),
    ]
