# Generated by Django 5.2.9 on 2026-05-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicepackage_setup_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='who_its_for',
            field=models.TextField(blank=True, help_text="One ideal client type per line (e.g. 'Small business owners', 'SaaS founders')", verbose_name="Who It's For"),
        ),
    ]
