# Generated by Django 5.2.9 on 2026-01-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_service_package_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of order', max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
