# Generated by Django 5.2.9 on 2026-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pricing_type',
            field=models.CharField(choices=[('buyout', 'Buyout (Own)'), ('subscription', 'Monthly Subscription')], default='buyout', max_length=20, verbose_name='Pricing Type'),
        ),
    ]
