# Generated by Django 5.2.9 on 2026-06-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_budget_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeline',
            field=models.CharField(blank=True, choices=[('asap', 'As soon as possible'), ('1_month', 'Within 1 month'), ('1_3_months', '1 – 3 months'), ('3_6_months', '3 – 6 months'), ('flexible', 'Flexible / just exploring')], max_length=20, verbose_name='Timeline'),
        ),
    ]
