# Generated by Django 5.2.9 on 2026-05-27 17:39

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Business Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('url', models.URLField(blank=True, help_text='Public website for this business', verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('business_name', models.CharField(max_length=200, verbose_name='Business Name')),
                ('business_url', models.URLField(blank=True, verbose_name='Business Website')),
                ('description', models.TextField(blank=True, help_text='What does your business do? What courses do you plan to offer?', verbose_name='About Your Business')),
                ('google_profile_url', models.URLField(blank=True, help_text='Link to your Google Business Profile for verification', verbose_name='Google Business Profile URL')),
                ('is_google_verified', models.BooleanField(default=False, help_text='Set automatically when applicant has a linked Google account', verbose_name='Google Verified')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('linked_business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='courses.business', verbose_name='Linked Business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_application', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Business Application',
                'verbose_name_plural': 'Business Applications',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BusinessComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('body', models.TextField(max_length=1000, verbose_name='Comment')),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to hide spam or abusive comments', verbose_name='Visible')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business Comment',
                'verbose_name_plural': 'Business Comments',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Downtown Branch, Chicago Office, Classroom A', max_length=200, verbose_name='Location Name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State / Region')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='courses.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business Location',
                'verbose_name_plural': 'Business Locations',
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('display_name', models.CharField(blank=True, help_text='Public alias shown instead of real name. Leave blank to use username.', max_length=100, verbose_name='Display Name / Alias')),
                ('bio', models.TextField(blank=True, help_text='Short public bio (max 500 characters)', max_length=500, verbose_name='Bio')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Photo')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Share Token')),
                ('is_public', models.BooleanField(default=False, help_text='When off: share link shows username + join date + photo only. When on: completed courses are visible.', verbose_name='Public Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('title', models.CharField(blank=True, help_text='e.g. Lead Instructor, Senior Developer', max_length=200, verbose_name='Title / Role')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('url', models.URLField(blank=True, help_text='Personal site, LinkedIn, etc.', verbose_name='Profile URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Photo')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='courses.business', verbose_name='Business')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='courses.businesslocation', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('skills', models.TextField(blank=True, help_text='One skill per line (e.g. Python, Django, REST APIs)', verbose_name='Skills Taught')),
                ('is_open', models.BooleanField(default=False, help_text='Requires at least one teacher assigned before enabling', verbose_name='Open for Registration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.business', verbose_name='Business')),
                ('location', models.ForeignKey(blank=True, help_text='Optional: tie this course to a specific location or classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.businesslocation', verbose_name='Location / Classroom')),
                ('teachers', models.ManyToManyField(blank=True, help_text='At least one teacher is required to open registration', related_name='courses', to='courses.teacher', verbose_name='Teachers')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['business', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Certificate ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-created'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
