#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput

exec gunicorn config.wsgi \
  --bind 0.0.0.0:5000 \
  --chdir=/app \
  --workers="${WEB_CONCURRENCY:-4}" \
  --max-requests=1000 \
  --max-requests-jitter=100 \
  --timeout=120 \
  --access-logfile=- \
  --error-logfile=- \
  --log-level=info
