# Generated by Django 5.2.9 on 2026-03-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Author'),
        ),
    ]
