# Generated by Django 5.2.9 on 2026-01-03 02:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('planning', 'Planning'), ('design', 'Design'), ('development', 'Development'), ('review', 'Review'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Progress %')),
                ('estimated_completion', models.DateField(blank=True, null=True, verbose_name='Estimated Completion')),
                ('actual_completion', models.DateField(blank=True, null=True, verbose_name='Actual Completion')),
                ('status_notes', models.TextField(blank=True, help_text='Current status description for client', verbose_name='Status Notes')),
                ('client', models.ForeignKey(help_text='User who can view this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='Payment Method')),
                ('invoice_file', models.FileField(blank=True, upload_to='invoices/', verbose_name='Invoice PDF')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Invoice',
                'verbose_name_plural': 'Project Invoices',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Update Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='project_updates/', verbose_name='Update Image')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('client_feedback', models.TextField(blank=True, verbose_name='Client Feedback')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'ordering': ['-created'],
            },
        ),
    ]
