# Generated by Django 5.2.9 on 2026-01-08 14:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Progress %')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Item',
                'verbose_name_plural': 'Project Items',
                'ordering': ['display_order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Milestone Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['display_order', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField(verbose_name='Content')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment', upload_to='project_notes/', verbose_name='Attachment')),
                ('is_internal', models.BooleanField(default=False, help_text='Only visible to staff', verbose_name='Internal Note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('item', models.ForeignKey(blank=True, help_text='Link note to specific item (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.projectitem', verbose_name='Project Item')),
                ('parent', models.ForeignKey(blank=True, help_text='Reply to another note', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.projectnote', verbose_name='Parent Note')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Note',
                'verbose_name_plural': 'Project Notes',
                'ordering': ['created'],
            },
        ),
    ]
