# Generated by Django 5.2.9 on 2026-01-08 14:53

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectitem_projectmilestone_projectnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revised', 'Needs Revision')], default='pending', max_length=20)),
                ('document', models.FileField(blank=True, help_text='Upload document, image, or design file', upload_to='project_approvals/', verbose_name='Document/Image')),
                ('client_decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Decision Date')),
                ('client_notes', models.TextField(blank=True, help_text='Client feedback or rejection reason', verbose_name='Client Notes')),
                ('requires_response', models.BooleanField(default=True, help_text='Whether client needs to approve/reject', verbose_name='Requires Client Response')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Approval',
                'verbose_name_plural': 'Project Approvals',
                'ordering': ['-created'],
            },
        ),
    ]
