# Generated by Django 5.2.9 on 2026-01-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from project name', max_length=220, unique=True, verbose_name='Slug'),
        ),
    ]
