# Generated by Django 5.2.9 on 2026-01-16 16:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('github_repo_url', models.URLField(help_text='Full URL to the GitHub repository (e.g., https://github.com/user/repo)', verbose_name='GitHub Repository URL')),
                ('github_branch', models.CharField(default='main', help_text='Branch to deploy (default: main)', max_length=100, verbose_name='Branch')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for validating GitHub webhook requests', max_length=64, verbose_name='Webhook Secret')),
                ('container_id', models.CharField(blank=True, help_text='Docker container ID when running', max_length=64, verbose_name='Container ID')),
                ('image_name', models.CharField(blank=True, help_text='Docker image name for this deployment', max_length=200, verbose_name='Image Name')),
                ('internal_port', models.IntegerField(default=8000, help_text='Port the application listens on inside the container', verbose_name='Internal Port')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning Repository'), ('building', 'Building Image'), ('starting', 'Starting Container'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Deployed')),
                ('build_log', models.TextField(blank=True, help_text='Output from the last build/deploy attempt', verbose_name='Build Log')),
                ('preview_token', models.UUIDField(default=uuid.uuid4, help_text='Token for public preview access', unique=True, verbose_name='Preview Token')),
                ('memory_limit', models.CharField(default='256m', help_text='Container memory limit (e.g., 256m, 512m)', max_length=20, verbose_name='Memory Limit')),
                ('cpu_limit', models.FloatField(default=0.5, help_text='CPU limit (0.5 = half a core)', verbose_name='CPU Limit')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Deployment',
                'verbose_name_plural': 'Project Deployments',
            },
        ),
    ]
