# Generated by Django 5.2.9 on 2026-03-25 17:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='account_manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Account Manager Email'),
        ),
        migrations.AddField(
            model_name='project',
            name='account_manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Account Manager Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='account_manager_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account Manager Phone'),
        ),
        migrations.AddField(
            model_name='project',
            name='account_manager_title',
            field=models.CharField(blank=True, help_text='e.g. Project Lead, Creative Director', max_length=200, verbose_name='Account Manager Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='beta_password',
            field=models.CharField(blank=True, help_text='Test account password for the beta site (visible to client)', max_length=200, verbose_name='Beta Password'),
        ),
        migrations.AddField(
            model_name='project',
            name='beta_username',
            field=models.CharField(blank=True, help_text='Test account username for the beta site (visible to client)', max_length=200, verbose_name='Beta Username'),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Discovery, Scope Definition, Architecture, Development', max_length=200, verbose_name='Phase Name')),
                ('description', models.TextField(blank=True, help_text='Updates or notes visible to the client for this phase', verbose_name='Client Notes')),
                ('progress_percentage', models.IntegerField(default=0, help_text='0–100. Admin sets this; client sees the progress bar.', verbose_name='Progress %')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Phase',
                'verbose_name_plural': 'Project Phases',
                'ordering': ['display_order', 'created'],
            },
        ),
        migrations.AddField(
            model_name='projectapproval',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='projects.projectphase', verbose_name='Phase'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='projects.projectphase', verbose_name='Phase'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='projects.projectphase', verbose_name='Phase'),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='projects.projectphase', verbose_name='Phase'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Link to a specific project phase (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='projects.projectphase', verbose_name='Phase'),
        ),
        migrations.CreateModel(
            name='ProjectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('question', models.TextField(help_text='The question or instruction shown to the client', verbose_name='Question')),
                ('question_type', models.CharField(choices=[('text', 'Free Text'), ('confirm', 'Confirm / Acknowledge'), ('choice', 'Select from Options')], default='text', help_text='Free Text = client writes an answer. Confirm = client ticks a checkbox. Choice = client picks from a list.', max_length=10, verbose_name='Question Type')),
                ('choices', models.TextField(blank=True, help_text="For 'Select from Options' type only — one option per line (e.g. brand slogans, language tones).", verbose_name='Options')),
                ('attachment', models.FileField(blank=True, help_text='Optional image, PDF, or document the client should review before answering', upload_to='project_questions/', verbose_name='Attachment')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('answer', models.TextField(blank=True, verbose_name='Client Answer')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Answered At')),
                ('status', models.CharField(choices=[('pending', 'Awaiting Response'), ('answered', 'Answered')], default='pending', max_length=10)),
                ('phase', models.ForeignKey(blank=True, help_text='Which phase this question belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.projectphase', verbose_name='Phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Question',
                'verbose_name_plural': 'Project Questions',
                'ordering': ['display_order', 'created'],
            },
        ),
    ]
