# Generated by Django 5.2.9 on 2026-03-25 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_account_manager_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text="Other users who can view this project dashboard (e.g. client's team members)", related_name='collaborated_projects', to=settings.AUTH_USER_MODEL, verbose_name='Additional Team Members'),
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Optional external payment link (PayPal, Stripe, Square, etc.)', verbose_name='Payment Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(help_text='Primary client user for this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
