# Generated by Django 5.2.9 on 2026-01-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_company_name_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_contacts',
            field=models.TextField(blank=True, help_text='Additional contact information (e.g., team members, alternative emails)', verbose_name='Additional Contacts'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Website'),
        ),
    ]
