# Generated by Django 5.2.9 on 2026-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_additional_contacts_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('business_applicant', 'Business — Pending Approval'), ('business', 'Business')], default='student', max_length=20, verbose_name='Account Type'),
        ),
    ]
